os: 
- linux
#- windows
dist: trusty
language: java


script:
#- if [[ $TRAVIS_OS_NAME == 'windows' ]]; then bash deploy_test_win.sh; fi
#- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then bash deploy_test_linux.sh; fi
- KNIME_FILE="knime_3.7.2.linux.gtk.x86_64.tar.gz"
- wget -q "http://download.knime.org/analytics-platform/linux/$KNIME_FILE"
- tar -xzf $KNIME_FILE
- rm $KNIME_FILE
- bash deploy_test_linux.sh

before_install:
- chmod +x deploy_test_linux.sh
# Install R 3.2 instead of R 3.0 from base Ubuntu
- |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]
  then
    sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
    sudo apt-get --allow-unauthenticated update -qq
    sudo apt-get --allow-unauthenticated install r-base -qq
    # Install packages
    sudo apt-get install libcurl4-openssl-dev libxml2-dev libssl-dev -qq
    sudo R --vanilla -e 'install.packages(c("Rserve", "miniCRAN", "ggplot2", "svglite"), repos="https://cran.rstudio.com", Ncpus=2)'
    chmod +x deploy_test_linux.sh
  fi
  
- |
  if [[ $TRAVIS_OS_NAME == 'windows' ]]
  then
    chmod +x deploy_test_win.sh
  fi
  
      